/**
 * An in-process JSON-RPC endpoint for the relayer's unit tests.
 *
 * This is a transport double, not a contract double: the tests still build real
 * `ethers.Contract` objects from the ABIs generated by `scripts/export-relayer-abis.js`
 * and let ethers do all of the ABI encoding, decoding, transaction signing and
 * revert decoding. Only the wire between the two is answered locally, which is
 * what makes it possible to unit test the watcher without an RPC endpoint.
 *
 * Usage:
 *
 *   const chain = await createChain();
 *   chain.onCall(routerAddress, 'getBridgeRequest', ([requestId]) => [request, 1]);
 *   chain.onCall(routerAddress, 'recordInbound', () => { throw chain.revert('AlreadyRecorded'); });
 *   const provider = new ethers.providers.JsonRpcProvider(chain.url);
 *
 * Handlers receive the decoded arguments (`(args, tx)`) and return either a
 * single value, an array of return values, or `undefined` for no return data.
 * Throw `chain.revert('ErrorName')` to answer with a real encoded custom error.
 */
const http = require('http');
const { ethers } = require('ethers');

const DEFAULT_CHAIN_ID = 31337;

async function createChain({ chainId = DEFAULT_CHAIN_ID, blockNumber = 100, contracts = {} } = {}) {
  const handlers = new Map(); // "address:selector" -> handler
  const code = new Map(); // address -> deployed bytecode marker
  const receipts = new Map();
  const sent = [];
  const logs = [];
  let currentBlock = blockNumber;

  for (const address of Object.keys(contracts)) {
    code.set(address.toLowerCase(), '0x6001600101');
  }

  function key(address, selector) {
    return `${address.toLowerCase()}:${selector.toLowerCase()}`;
  }

  function interfaceFor(address) {
    const abi = contracts[address.toLowerCase()] || contracts[address];
    if (!abi) throw new Error(`no ABI registered for ${address}`);
    return new ethers.utils.Interface(abi);
  }

  /** Registers a handler for `contractName.methodName`. */
  function onCall(address, method, handler) {
    const iface = interfaceFor(address);
    const fragment = iface.getFunction(method);
    handlers.set(key(address, iface.getSighash(fragment)), { iface, fragment, handler });
    return api;
  }

  /** Registers a read-only fallback that always returns `value` for a method. */
  function onStaticCall(address, method, value) {
    return onCall(address, method, () => value);
  }

  /**
   * Builds a revert carrying a real encoded custom error.
   *
   * `Error(string)` is a Solidity builtin and cannot be declared in an ABI, so
   * passing a free-text message encodes the builtin selector by hand.
   */
  function revert(name, args = []) {
    const abi = contracts.__errorAbi || [];
    try {
      const iface = new ethers.utils.Interface(abi);
      return { data: iface.encodeErrorResult(name, args) };
    } catch (e) {
      const encoded = ethers.utils.defaultAbiCoder.encode(['string'], [`execution reverted: ${name}`]);
      return { data: ethers.utils.id('Error(string)').slice(0, 10) + encoded.slice(2) };
    }
  }

  function jsonrpcError(id, error) {
    return {
      jsonrpc: '2.0',
      id,
      error: { code: 3, message: 'execution reverted', data: error.data }
    };
  }

  async function handleRequest(body) {
    const { method, params = [], id } = body;

    switch (method) {
      case 'eth_chainId':
        return '0x' + chainId.toString(16);
      case 'net_version':
        return String(chainId);
      case 'eth_blockNumber':
        return '0x' + currentBlock.toString(16);
      case 'eth_gasPrice':
        return '0x3b9aca00';
      case 'eth_getTransactionCount':
        return '0x0';
      case 'eth_accounts':
        return [];
      case 'eth_getCode': {
        const address = String(params[0]).toLowerCase();
        return code.get(address) || '0x';
      }
      case 'eth_estimateGas': {
        // Route through the same handler as the write itself: a reverting
        // contract reverts at estimation time too (ethers surfaces it here
        // before the transaction is signed and broadcast).
        const tx = params[0];
        if (tx && tx.data) {
          const entry = handlers.get(key(tx.to, tx.data.slice(0, 10)));
          if (entry) {
            const decoded = entry.iface.decodeFunctionData(entry.fragment, tx.data);
            await entry.handler(decoded, tx);
          }
        }
        return '0x186a0';
      }
      case 'eth_call': {
        const tx = params[0];
        const selector = tx.data.slice(0, 10);
        const entry = handlers.get(key(tx.to, selector));
        if (!entry) {
          throw { code: -32000, message: `no handler for ${tx.to} ${selector}` };
        }
        const decoded = entry.iface.decodeFunctionData(entry.fragment, tx.data);
        const result = await entry.handler(decoded, tx);
        if (result === undefined) return '0x';
        const outputs = entry.fragment.outputs || [];
        const values = Array.isArray(result) && outputs.length > 1 ? result : [result];
        return entry.iface.encodeFunctionResult(entry.fragment, values);
      }
      case 'eth_sendRawTransaction': {
        const parsed = ethers.utils.parseTransaction(params[0]);
        const hash = ethers.utils.keccak256(params[0]);
        const selector = parsed.data.slice(0, 10);
        const entry = handlers.get(key(parsed.to, selector));
        const record = {
          hash,
          from: parsed.from,
          to: parsed.to,
          data: parsed.data,
          value: parsed.value,
          nonce: parsed.nonce,
          blockNumber: currentBlock,
          method: entry ? entry.fragment.name : undefined
        };
        sent.push(record);
        receipts.set(hash, {
          transactionHash: hash,
          transactionIndex: '0x0',
          blockHash: '0x' + '11'.repeat(32),
          blockNumber: '0x' + currentBlock.toString(16),
          from: parsed.from,
          to: parsed.to,
          cumulativeGasUsed: '0x5208',
          gasUsed: '0x5208',
          contractAddress: null,
          logs: logs.filter((l) => l.transactionHash === hash),
          logsBloom: '0x' + '00'.repeat(256),
          status: '0x1',
          type: '0x2',
          effectiveGasPrice: '0x3b9aca00'
        });
        currentBlock += 1;
        return hash;
      }
      case 'eth_getTransactionReceipt': {
        const hash = String(params[0]).toLowerCase();
        return receipts.get(hash) || null;
      }
      case 'eth_getTransactionByHash': {
        const hash = String(params[0]).toLowerCase();
        const record = sent.find((tx) => tx.hash.toLowerCase() === hash);
        if (!record) return null;
        return {
          hash: record.hash,
          from: record.from,
          to: record.to,
          value: record.value,
          nonce: record.nonce,
          blockNumber: '0x' + record.blockNumber.toString(16),
          blockHash: '0x' + '11'.repeat(32),
          transactionIndex: '0x0',
          gas: '0x186a0',
          gasPrice: '0x3b9aca00',
          input: record.data,
          chainId: '0x' + chainId.toString(16),
          type: 2
        };
      }
      case 'eth_getBlockByNumber': {
        const number = params[0] === 'latest' ? currentBlock : parseInt(params[0], 16);
        return {
          number: '0x' + number.toString(16),
          hash: '0x' + '11'.repeat(32),
          parentHash: '0x' + '22'.repeat(32),
          timestamp: 1700000000 + number,
          transactions: [],
          gasLimit: '0x1c9c380',
          gasUsed: '0x0',
          miner: ethers.constants.AddressZero,
          difficulty: '0x0',
          baseFeePerGas: '0x3b9aca00',
          extraData: '0x'
        };
      }
      case 'eth_feeHistory':
        return {
          oldestBlock: '0x' + currentBlock.toString(16),
          baseFeePerGas: ['0x3b9aca00', '0x3b9aca00'],
          gasUsedRatio: [0],
          reward: [['0x3b9aca00']]
        };
      default:
        throw { code: -32601, message: `method not supported by the test chain: ${method}` };
    }
  }

  const server = http.createServer((req, res) => {
    let raw = '';
    req.on('data', (chunk) => (raw += chunk));
    req.on('end', async () => {
      const body = JSON.parse(raw || '{}');
      const respond = async (call) => {
        try {
          const result = await handleRequest(call);
          return { jsonrpc: '2.0', id: call.id, result };
        } catch (error) {
          if (error && error.data) return jsonrpcError(call.id, error);
          return {
            jsonrpc: '2.0',
            id: call.id,
            error: { code: error.code || -32000, message: error.message }
          };
        }
      };
      const payload = Array.isArray(body)
        ? await Promise.all(body.map(respond))
        : await respond(body);
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(JSON.stringify(payload));
    });
  });

  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${server.address().port}`;

  const api = {
    url,
    chainId,
    onCall,
    onStaticCall,
    revert,
    sent,
    logs,
    /** Emits a receipt log (useful for event assertions). */
    emit(hash, log) {
      logs.push({ ...log, transactionHash: hash });
    },
    async close() {
      await new Promise((resolve) => server.close(resolve));
    }
  };

  return api;
}

module.exports = { createChain };
