#!/usr/bin/env node
/**
 * Prepares the relayer for a Sepolia deployment.
 *
 * Contract deployment itself belongs to the repository's Hardhat scripts:
 *
 *   npx hardhat run scripts/deploy.js --network sepolia
 *   npx hardhat run scripts/setup-trusted-remotes.js --network sepolia
 *
 * This script does the relayer half: it takes the deployed addresses, verifies
 * on-chain that the relayer account is actually allowed to do its job (adapter
 * registered, relayer authorised, bridge timeout set), and writes the
 * environment file the service reads. It refuses to write a configuration that
 * would fail at the first inbound transfer.
 *
 *   HYPERDEX_ADDRESS=0x... BRIDGE_ROUTER_ADDRESS=0x... DST_CHAIN_ID=10 \
 *   SRC_CHAIN_ID=11155111 RELAYER_PRIVATE_KEY=0x... SEPOLIA_RPC_URL=... \
 *   node relayer/scripts/deploy-sepolia.js
 *
 * Add DRY_RUN=1 to print the configuration without writing it.
 */
const fs = require('fs');
const path = require('path');
const { ethers } = require('ethers');

const BridgeRouterABI = require('../abi/BridgeRouter.json');
const HyperDexABI = require('../abi/HyperDex.json');

function requireEnv(name) {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is required`);
  return value;
}

async function main() {
  const rpcUrl = requireEnv('SEPOLIA_RPC_URL');
  const privateKey = requireEnv('RELAYER_PRIVATE_KEY');
  const hyperDexAddress = requireEnv('HYPERDEX_ADDRESS');
  const routerAddress = requireEnv('BRIDGE_ROUTER_ADDRESS');
  const srcChainId = Number(requireEnv('SRC_CHAIN_ID'));
  const dstChainId = Number(requireEnv('DST_CHAIN_ID'));

  const provider = new ethers.providers.JsonRpcProvider(rpcUrl);
  const wallet = new ethers.Wallet(privateKey, provider);
  const { chainId } = await provider.getNetwork();

  if (Number(chainId) !== srcChainId) {
    throw new Error(
      `RPC endpoint is on chain ${chainId} but SRC_CHAIN_ID is ${srcChainId}`
    );
  }

  console.log(`Relayer ${wallet.address} on chain ${chainId}`);

  // --- HyperDex gateway -----------------------------------------------------
  const hyperDex = new ethers.Contract(hyperDexAddress, HyperDexABI, provider);
  const onChainRelayer = await hyperDex.relayer();
  if (onChainRelayer.toLowerCase() !== wallet.address.toLowerCase()) {
    throw new Error(
      `HyperDex.relayer is ${onChainRelayer}, not ${wallet.address}. ` +
        'The owner must call setRelayer(address) before this account can submit gasless swaps.'
    );
  }
  console.log(`  HyperDex gateway ${hyperDexAddress}: relayer authorised`);

  // --- Bridge router --------------------------------------------------------
  const router = new ethers.Contract(routerAddress, BridgeRouterABI, provider);

  const authorised = await router.authorizedRelayers(wallet.address);
  if (!authorised) {
    throw new Error(
      `${wallet.address} is not an authorised relayer on ${routerAddress}; ` +
        'inbound requests cannot be recorded or completed.'
    );
  }
  console.log(`  BridgeRouter ${routerAddress}: relayer authorised`);

  const adapter = await router.bridgeAdapters(dstChainId);
  if (adapter === ethers.constants.AddressZero) {
    throw new Error(
      `No adapter registered for destination chain ${dstChainId}; ` +
        'the inbound leg would revert with InvalidAdapter.'
    );
  }
  console.log(`  destination chain ${dstChainId} -> adapter ${adapter}`);

  const timeout = await router.bridgeTimeout();
  console.log(`  bridge timeout: ${timeout.toString()}s`);

  // --- Output ---------------------------------------------------------------
  const env = [
    `# Generated by relayer/scripts/deploy-sepolia.js on ${new Date().toISOString()}`,
    `NODE_ENV=production`,
    `PORT=3000`,
    `RPC_URL=${rpcUrl}`,
    `SRC_CHAIN_ID=${srcChainId}`,
    `DST_CHAIN_ID=${dstChainId}`,
    `HYPERDEX_ADDRESS=${hyperDexAddress}`,
    `BRIDGE_ROUTER_SOURCE=${routerAddress}`,
    `BRIDGE_ROUTER_DEST=${process.env.BRIDGE_ROUTER_DEST || routerAddress}`,
    `RELAYER_ADDRESS=${wallet.address}`,
    ''
  ].join('\n');

  const outPath = path.join(__dirname, '..', '.env.sepolia');
  if (process.env.DRY_RUN === '1') {
    console.log('\n(dry run) would write', outPath, '\n');
    console.log(env);
    return;
  }

  fs.writeFileSync(outPath, env, { mode: 0o600 });
  console.log(`\nWrote ${outPath} (mode 0600).`);
  console.log('Next: configure the destination adapter address, then start the relayer.');
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
